---
# TODO: secure access to mesos master UI
# TODO: replace UI with https://github.com/Capgemini/mesos-ui
#
- name: gather list of installed nix packages
  shell: |
    . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
    nix-env -qa > {{ nix_home }}/nix-env.qa
  become: yes
  become_user: '{{ nix_user }}'
  tags:
    - mesos-master
    - apache-maven
    - openjdk

# TODO: there is one package for the mesos-master and slave.
# this means that when the mesos-master playbook updates the mesos package
# it will trigger a notify to restart the mesos-master service.
# However a run of the mesos-slave playbook won't trigger the restart of the
# mesos-slave service as it won't find a package to upgrade.
- name: installing mesos through nix
  shell: |
    if ! grep -q "{{ item }}" {{ nix_home}}/nix-env.qa; then
      . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
      nix-env -f ~/.nix-defexpr/channels/nixos-16.03/nixpkgs/ -i {{ item }}
      echo "mesos-master.changed"
    fi
  args:
    executable: '{{ nix_shell }}'
  become: yes
  become_user: '{{ nix_user }}'
  register: mesos
  changed_when: "'mesos-master.changed' in mesos.stdout"
  with_items:
    - apache-maven
    - openjdk
    - mesos-0.27.1
  notify:
    - reload systemd
    - restart-mesos-master
  tags:
    - mesos-master
    - apache-maven
    - openjdk

- name: create required directories
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    state=directory
    recurse=yes
  with_items:
    - { path: '{{ mesos_master_datadir }}', owner: '{{ nix_user }}', group: '{{ nix_group }}' }
    - { path: '{{ mesos_master_logdir }}', owner: '{{ nix_user }}', group: '{{ nix_group}}' }
    - { path: '{{ mesos_master_bindir }}', owner: '{{ nix_user }}', group: '{{ nix_group}}' }
    - { path: '{{ mesos_master_confdir }}', owner: '{{ nix_user }}', group: '{{ nix_group}}' }
  tags:
    - mesos-master
    - marathon

- name: deploying mesos-master files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner='root'
  with_items:
    - { src: 'etc.systemd.system.mesos-master.service',
        dest: '/etc/systemd/system/mesos-master.service' }
  notify:
    - reload systemd
    - restart-mesos-master
  tags:
    - mesos-master
    - systemd

- name: create mesos-master credential file
  copy:
    content='{{ mesos_master_credentials }}'
    dest='{{ mesos_master_credentials_file }}'
    owner='{{ nix_user }}'
    group='{{ nix_group }}'
  notify:
    - reload systemd
    - restart-mesos-master
  tags:
    - mesos-master
    - systemd

- name: start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - mesos-master
  tags:
    - mesos-master
    - systemd



