---

- hosts:
  - centos7
  - suse12

  sudo: True

  roles:
    - os-updates
    - virtualbox
    - vagrant
    - mesos
    - docker

  #tasks:
    #- name: adding epel repository
      #yum:
        #name=epel-release
        #state=present






