---

- hosts:
  - centos7
  - suse12
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - os-updates
    - virtualbox
    - vagrant
    - { role: nix, when: "'{{ ansible_os_family }}' == 'Suse'" }
    - { role: nix-zookeeper, when: "'{{ ansible_os_family }}' == 'Suse'" }
    - { role: nix-mesos-master, when: "'{{ ansible_os_family }}' == 'Suse'" }
    - { role: nix-mesos-slave, when: "'{{ ansible_os_family }}' == 'Suse'" }
    - { role: nix-marathon, when: "'{{ ansible_os_family }}' == 'Suse'" }
    - { role: mesos, when: "'{{ ansible_os_family }}' == 'RedHat'" }
    - { role: docker, when: "'{{ ansible_os_family }}' == 'RedHat'" }
    - { role: nix-docker, when: "'{{ ansible_os_family }}' == 'Suse'" }
