---

- hosts:
  - centos7
  - suse12
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - os-updates
    #- virtualbox
    #- vagrant
    - nix
    - nix-mesos
      # - mesos
      #- docker

  #tasks:
    #- name: adding epel repository
      #yum:
        #name=epel-release
        #state=present






