---

- name: make sure we have the required dependencies installed
  zypper:
    name={{ item.name }}
    state={{ item.state }}
  with_items:
    - { name: 'patterns-openSUSE-minimal_base-conflicts', state: 'absent' }
    - { name: 'python', state: 'latest' }
    - { name: 'python-xml', state: 'latest' }
    - { name: 'make', state: 'latest' }
    - { name: 'gcc', state: 'latest' }
    - { name: 'gcc-c++', state: 'latest' }
    - { name: 'kernel-source', state: 'latest' }
    - { name: 'kernel-syms', state: 'latest' }
  when: ansible_os_family == 'Suse'
  tags:
    - virtualbox

- name: checking if vboxdrv kernel module is loaded
  command: lsmod
  register: lsmod
  tags:
    - virtualbox

- name: download virtualbox key
  get_url:
    url=https://www.virtualbox.org/download/oracle_vbox.asc
    validate_certs=False
    dest=/tmp/oracle_vbox.asc
    use_proxy=yes
  when: lsmod.stdout.find('vboxdrv') == -1
  tags:
    - virtualbox

- name: adding virtualbox key
  rpm_key:
    key=/tmp/oracle_vbox.asc
    state=present
    validate_certs=False
  when: lsmod.stdout.find('vboxdrv') == -1
  tags:
    - virtualbox

- name: adding virtualbox repository
  get_url:
    url=http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
    dest=/etc/yum.repos.d/virtualbox.repo
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'RedHat'
  tags:
    - virtualbox


- name: adding virtualbox repository
  zypper_repository:
    repo=http://download.virtualbox.org/virtualbox/rpm/opensuse/12.3/virtualbox.repo
    state=present
    refresh=yes
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'Suse'
  tags:
    - virtualbox

- name: installing virtualbox
  yum:
    name={{ item }}
    state=latest
    update_cache=yes
  with_items:
    - kernel-devel
    - VirtualBox-5.0
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'RedHat'
  tags:
    - virtualbox

- name: installing virtualbox
  zypper:
    name={{ item }}
    state=latest
  with_items:
    - kernel-devel
    - VirtualBox-5.0
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'Suse'
  tags:
    - virtualbox


- name: checking if vboxdrv kernel module is loaded
  command: lsmod
  register: lsmod
  tags:
    - virtualbox

- name: recompiling virtualbox driver
  shell: |
    KERN_DIR=/usr/src/kernels/`rpm -q kernel-devel --queryformat '%{version}-%{release}.%{arch}'` \
    /usr/lib/virtualbox/vboxdrv.sh setup
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'RedHat'
  tags:
    - virtualbox

- name: recompiling virtualbox driver
  shell: |
    /usr/lib/virtualbox/vboxdrv.sh setup
  when: lsmod.stdout.find('vboxdrv') == -1 and ansible_os_family == 'Suse'
  tags:
    - virtualbox

- name: adding user to vboxusers
  user:
    name={{ lookup('env','USER') }}
    groups='vboxusers'
    append=yes
  tags:
    - virtualbox

- name: enabling vboxdrv service
  service:
    name=vboxdrv
    state=started
    enabled=yes
  tags:
    - virtualbox
