---

- name: gather list of installed nix packages
  shell: |
    . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
    nix-env -qa > {{ nix_home }}/nix-env.qa
  become: yes
  become_user: '{{ nix_user }}'

- name: installing marathon through nix
  shell: |
    if ! grep -q "{{ item }}" {{ nix_home}}/nix-env.qa; then
      . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
      nix-env -f ~/.nix-defexpr/channels/nixos-16.03/nixpkgs/ -i {{ item }}
    fi
  args:
    executable: '{{ nix_shell }}'
  become: yes
  become_user: '{{ nix_user }}'
  with_items:
    - marathon
    - apache-maven
    - openjdk
  notify:
    - reload systemd
    - restart-marathon
  tags:
    - marathon
    - apache-maven
    - openjdk


- name: deploying marathon files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner='root'
  with_items:
    - { src: 'etc.systemd.system.marathon.service',
        dest: '/etc/systemd/system/marathon.service' }
  notify:
    - reload systemd
    - restart-marathon
  when: ansible_os_family == 'Suse'
  tags:
    - marathon
    - systemd


- name: start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - marathon
  when: ansible_os_family == 'Suse'
  tags:
    - marathon
    - systemd



