---

- name: gather list of installed nix packages
  shell: |
    . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
    nix-env -qa > {{ nix_home }}/nix-env.qa
  become: yes
  become_user: '{{ nix_user }}'

- name: installing mesos through nix
  shell: |
    if ! grep -q "{{ item }}" {{ nix_home}}/nix-env.qa; then
      . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
      nix-env -f ~/.nix-defexpr/channels/nixos-16.03/nixpkgs/ -i {{ item }}
    fi
  args:
    executable: '{{ nix_shell }}'
  become: yes
  become_user: '{{ nix_user }}'
  with_items:
    - mesos-0.27.1
    - apache-maven
    - openjdk
  notify:
    - reload systemd
    - restart-mesos-slave
  tags:
    - mesos-slave
    - apache-maven
    - openjdk


- name: create required directories
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    state=directory
    recurse=yes
  with_items:
    - { path: '{{ mesos_slave_datadir }}', owner: '{{ nix_user }}' }
    - { path: '{{ mesos_slave_logdir }}', owner: '{{ nix_user }}' }
    - { path: '{{ mesos_slave_bindir }}', owner: '{{ nix_user }}' }
    - { path: '{{ mesos_slave_confdir }}', owner: '{{ nix_user }}' }
  tags:
    - mesos-slave


- name: deploying mesos-slave files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner='root'
  with_items:
    - { src: 'etc.systemd.system.mesos-slave.service',
        dest: '/etc/systemd/system/mesos-slave.service' }
  notify:
    - reload systemd
    - restart-mesos-slave
  tags:
    - mesos-slave
    - systemd


- name: start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - mesos-slave
  tags:
    - mesos-slave
    - systemd
