---
# fixes annonying grub2 bug
# kernel updates won't be selected at next boot
# https://bugzilla.redhat.com/show_bug.cgi?id=1124074
- name: upgrade grub
  yum: name=grub2
    state=latest
  when: ansible_os_family == 'RedHat'

- name: upgrade all packages
  yum: name=*
    state=latest
  when: ansible_os_family == 'RedHat'


- name: upgrade all packages
  command: zypper --non-interactive update
  when: ansible_os_family == 'Suse'

- name: Reboot host if kernel was upgraded
  shell: |
    if [ -e "/etc/SuSE-release" ]; then
      if [ "$(readlink -f /vmlinuz)" != "/boot/vmlinuz-$(uname -r)" ]; then
        echo "rebooting ..."
        sleep 2
        reboot
      fi
    else
      LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1)
      CURRENT_KERNEL=$(uname -r)
      if [ "$LAST_KERNEL" != "$CURRENT_KERNEL" ]; then
        echo "rebooting ..."
        sleep 2
        reboot
      fi
    fi
  args:
    executable: /bin/bash
  ignore_errors: true
  async: 1
  poll: 0

- name: Wait for thing to reboot...
  local_action:
    module: wait_for
      host={{ inventory_hostname | default(inventory_hostname) }}
      state=started
      delay=10
      search_regex=OpenSSH
  sudo: false
