---

- name: gather list of installed nix packages
  shell: |
    . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
    nix-env -q > {{ nix_home }}/nix-env.q
  become: yes
  become_user: '{{ nix_user }}'
  tags:
    - docker

- name: create docker group
  group:
    name=docker
    state=present
  tags:
    - docker

- name: add user to docker group
  user:
    name=nix
    append=yes
    groups=docker
  tags:
    - docker

- name: installing docker through nix
  shell: |
    if ! grep -q "{{ item }}" {{ nix_home}}/nix-env.q; then
      . {{ nix_home }}/.nix-profile/etc/profile.d/nix.sh
      nix-env -f ~/.nix-defexpr/channels/nixos-16.03/nixpkgs/ -i {{ item }}
      echo "docker.changed"
    fi
  args:
    executable: '{{ nix_shell }}'
  become: yes
  become_user: '{{ nix_user }}'
  register: docker
  changed_when: "'docker.changed' in docker.stdout"
  with_items:
    - docker
    - docker-compose
  notify:
    - reload systemd
    - restart-docker
  tags:
    - docker


- name: deploying docker files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner='root'
  with_items:
    - { src: 'etc.systemd.system.docker.service',
        dest: '/etc/systemd/system/docker.service' }
    - { src: 'etc.systemd.system.docker.socket',
        dest: '/etc/systemd/system/docker.socket' }
  notify:
    - reload systemd
    - restart-docker
  tags:
    - docker
    - systemd


- name: start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - docker
  tags:
    - docker
    - systemd
